version: "3.9"

services:
  api:
    container_name: pi-fastify
    build:
      dockerfile: Dockerfile
    working_dir: /code
    command: npm run start
    environment:
      DEBUG: 1
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    # network_mode: host
    restart: on-failure
