version: '3.3'
services:
    mssql:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=P4ssW0ordDB!1
        ports:
            - '1433:1433'
        container_name: sqlserver
        image: 'mcr.microsoft.com/mssql/server:2019-latest'