# still on progress, need Dockerfile
version: "3.9"

services:
  api:
    container_name: express-api-gate
    build: .
    working_dir: /app
    # command: npm run start 
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    # network_mode: host
    restart: on-failure
