version: "3.9"

services:
  api:
    container_name: fast-api
    build:
      context: .
      target: builder
    working_dir: /code/app
    command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:3000 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./app:/code/app
    ports:
      - '3000:3000'
    # network_mode: host
    restart: on-failure